Implements linkedlist banks, more thorough tests are still under work
lowRISC/gsoc-sim-mem pull request #1
Opened 2020-06-16 11:19 UTC by flaviens

Hi!

Here is the first (draft) pull request.
The main file to look at, for the moment, is rtl/simmem_linkedlist_bank.sv.

2020-06-30 15:29 UTC, GregAC requested changes
Hi @flaviens thanks for the PR.

I haven't reviewed everything in detail as I know you're working on a newer version plus it wasn't clear to me which modules are actually the ones you're planning on using, there seems to be more than what is instantiated under the top-level module included.

I've added various comments which can mostly be seen as more general points that apply to various things across the RTL rather than focused specifically at the line they're made against. I've avoided getting too deep into how the micro-architecture works but did have a few comments for the general approach I was seeing.

I worry this is trying to tackle many problems at once and for the initial work we should aim to keep things as simple as possible, even if this doesn't perform well or indeed doesn't work at all for various cases.

2020-06-30 15:29 UTC, GregAC commented on .gitignore
> +*~
I think this ignore file just came from OpenTitan? You may want to edit it down so it only includes things relevant to this project.

2020-06-30 15:29 UTC, GregAC commented on dv/simmem_write_resp_bank/cpp/simmem_write_resp_bank_tb.cc
> +#define RESET_LENGTH 5
in C++ prefer `const` variables to `#define`, also take note of how constants are named in the Google C++ style guide which we follow (https://google.github.io/styleguide/cppguide.html) e.g for `RESET_LENGTH` instead do:

```
const int kResetLength = 5;
```

2020-06-30 15:29 UTC, GregAC commented on dv/simmem_write_resp_bank/cpp/simmem_write_resp_bank_tb.cc
> +struct WriteRespBankTestbench {
The indentation is all over the place here, again note the indentation rules in the Google C++ style guide. You can use the 'clang-format' tool to automatically format code for you. The OpenTitan respository has a config file you can use: https://github.com/lowRISC/opentitan/blob/master/.clang-format

2020-06-30 15:29 UTC, GregAC commented on dv/simmem_write_resp_bank/cpp/simmem_write_resp_bank_tb.cc
> +struct WriteRespBankTestbench {
Also prefer `class` to `struct` where you've got both methods and data, `struct` is more appropriate for POD (plain old datatypes) where you only have public data members. Switching to class will mean you need to add `private:` and `public:` here placing the methods and data under appropriate access specifiers.

2020-06-30 15:29 UTC, GregAC commented on dv/simmem_write_resp_bank/cpp/simmem_write_resp_bank_tb.cc
> +	vluint32_t m_tick_count;
Please avoid hungarian notation (the `m_` for object members naming convention), a plain `_` following the name matches the style guide

```
vluint32_t tick_count_;
```

2020-06-30 15:29 UTC, GregAC commented on dv/simmem_write_resp_bank/cpp/simmem_write_resp_bank_tb.cc
> +    m_record_trace = record_trace;
Consider using a member intializer list: https://en.cppreference.com/w/cpp/language/constructor

```
WriteRespBankTestbench(vluint32_t max_clock_cycles = 0, bool record_trace = true, const std::string& trace_filename = "sim.fst") : 
  m_tick_count(0l), m_max_clock_cycles(max_clock_cycles), m_record_trace(record_trace) {
```

2020-06-30 15:29 UTC, GregAC commented on dv/simmem_write_resp_bank/cpp/simmem_write_resp_bank_tb.cc
> +	void destruct(void) {
Shouldn't this be a destructor?

```
~WriteRespBankTestbench() {
  delete m_module;
```

You could avoid it all together using C++ smart pointers, `std::unique_ptr` would probably be most appropriate here: https://docs.microsoft.com/en-us/cpp/cpp/how-to-create-and-use-unique-ptr-instances?view=vs-2019

2020-06-30 15:29 UTC, GregAC commented on dv/simmem_write_resp_bank/cpp/simmem_write_resp_bank_tb.cc
> +	void destruct(void) {
You may also need to close the trace if it's open here.

2020-06-30 15:29 UTC, GregAC commented on dv/simmem_write_resp_bank/cpp/simmem_write_resp_bank_tb.cc
> +    for (int i = 0; i < RESET_LENGTH; i++)
Even for single-line loops and ifs I'd use {} pairs. It's easy to forget they're not there and you end up with issues when you add a line or fail to realise a line is being captured by the if or for above.

2020-06-30 15:29 UTC, GregAC commented on dv/simmem_write_resp_bank/cpp/simmem_write_resp_bank_tb.cc
> +    printf("Running iteration %d.\n", m_tick_count);
Use std::cout for writing to stdout in C++

2020-06-30 15:29 UTC, GregAC commented on dv/simmem_write_resp_bank/cpp/simmem_write_resp_bank_tb.cc
> +      m_trace->dump(5*m_tick_count-1);
As above use {} even for single line if/loops

2020-06-30 15:29 UTC, GregAC commented on dv/simmem_write_resp_bank/cpp/simmem_write_resp_bank_tb.cc
> +// Copyright lowRISC contributors.
Consider using the simutil_verilator framework available in OpenTitan: https://github.com/lowRISC/opentitan/tree/master/hw/dv/verilator/simutil_verilator as it can handle most of what you're doing here for you so you can concentrate on the things relevant to the testbench.

2020-06-30 15:29 UTC, GregAC commented on rtl/simmem.sv
> +  input logic   read_addr_in_valid_i,
Some comments on what _in_ and _out_ are along with what these signals do and/or how they map to AXI would be useful.

2020-06-30 15:29 UTC, GregAC commented on rtl/simmem.sv
> +  output logic [WriteRespStructWidth-1:0]    write_resp_o
If these are all actual structures then use structures rather than `[ReadAddressStructWidth-1:0]`, e.g.

```
typedef struct packed {
  logic [7:0] ID;
  logic [31:0] addr;
} read_req_t;
```

Also consider more appropriate naming than `_addr` and `_data` if these contain things other than just address or data a more description name is needed.

2020-06-30 15:29 UTC, GregAC commented on rtl/simmem.sv
> +  logic [1:0][2**IDWidth-1] release_en;
This may be better off with a packed and unpacked dimension

```
logic [2**IDWidth-1] release_en [1:0];
```
Though I'd also question the 2 enable bits, this may be better expressed as two seperately named signals

```
logic [2**IDWidth-1] release_en_1;
logic [2**IDWidth-1] release_en_2;
```

With better names that explains what the two enables actually are.

2020-06-30 15:29 UTC, GregAC commented on rtl/simmem.sv
> +  output logic [WriteRespStructWidth-1:0]    write_resp_o
If you use structs you can ditch the need for the various `ReadAddressStructWidth` parameters.

Instead define the structs in a package file with parameters in the same package specifying things like a address and ID width.

2020-06-30 15:29 UTC, GregAC commented on rtl/simmem_message_banks.sv
> +  import simmem_pkg::ram_bank_e;
It's ok to use wildcard import within a module

```
import simmem_pkg::*;
```

2020-06-30 15:29 UTC, GregAC commented on rtl/simmem_message_banks.sv
> +    .release_en_i(release_en_i[READ_DATA]),
As mentioned elsewhere it would be better to have separate `release_read_en_i` and `release_write_en_i` signals.

2020-06-30 15:29 UTC, GregAC commented on rtl/simmem_message_banks.sv
> +  simmem_linkedlist_message_bank #(
Rather than having two entirely separate sets of message banks you could have one that provides enough storage per message to hold either a write response or read data. This will cut down on the usage of block RAMs. In FPGA even if you're not using much width the primitives may not be particularly narrow so even if the total number of bits you need to store for the write message bank is relatively low (compared to the read messages) it'll allocate block RAMs with lots of unused bits, e.g. if you have a 256 x 8-bit RAM this could map at a 256x32-bit primitive in the FPGA)

2020-06-30 15:29 UTC, GregAC commented on rtl/simmem_linkedlist_message_bank.sv
> +    .a_req_i     (req_ram[STRUCT_RAM][RAM_IN]),
Use named signals rather than packed/unpacked aarrays for things like this

```
logic req_struct_ram_in;
```

2020-06-30 15:29 UTC, GregAC commented on rtl/simmem_linkedlist_message_bank.sv
> +  logic [$clog2(TotalCapacity)-1:0] heads_d[2**IDWidth-1:0];
You can use a `localparam` to avoid repetition here as well as make the declarations simpler to understand. You should also not use the [n:0] syntax for unpacked dimensions, prefering `[n]` instead.

```systemverilog
localparam BankAddrWidth = $clog2(TotalCapacity);
localparam NumIDs = 2 ** IDWidth; // LIkely better off in the package file as it will be used in many places
...
logic [BankAddrWidth-1:0] heads_d [NumIDs];
```

2020-06-30 15:29 UTC, GregAC commented on rtl/simmem_linkedlist_message_bank.sv
> +  logic [$clog2(TotalCapacity)-1:0] linkedlist_length_q[2**IDWidth-1:0];
I don't think keeping track of the length is necessary, below you have different behaviour depending on whether length >= 2, length == 1, length != 0. Not sure that is required either but you can at least avoid keeping track of the full length and just track if length is 0, 1, 2 or greater than 2 (so 2 bits for 4 states and no adder/subtractor needed for updating).

2020-06-30 15:29 UTC, GregAC commented on rtl/simmem_linkedlist_message_bank.sv
> +  logic [StructWidth-IDWidth-1:0]
I wouldn't bother with output buffers to start with, it will just complicate matters, simply output directly from the RAM.

2020-06-30 15:29 UTC, GregAC commented on rtl/simmem_linkedlist_message_bank.sv
> +    assign ram_valid_d[current_addr] = ram_valid_q[current_addr] ^ (
It's quite hard to determine what this expression is trying to achieve, you may be better off with an `always_comb` block and some use of `if` to make its functionality more obvious, or if that doesn't work out more detailed commenting explaining what the expression does.

2020-06-30 15:29 UTC, GregAC commented on rtl/simmem_linkedlist_message_bank.sv
> +  logic [2**IDWidth-1:0] next_id_to_release_onehot_packed;
Any reason for the separate packed and unpacked versions? I think you can just have:

```systemverilog
logic [2**IDWidth-1:0] next_id_to_release_onehot;
```

2020-06-30 15:29 UTC, GregAC commented on rtl/simmem_linkedlist_message_bank.sv
> +  logic [StructWidth-1:0] data_o_id[2**IDWidth-1:0];
This would be a good reason to drop the output buffers, at one per ID and with say 256 IDs you end up implementing a gigantic mux to deal with it all. If you output directly from block RAMs you avoid this logic (which is likely to consume a lot of resource and may cause timing issues).

2020-06-30 15:29 UTC, GregAC commented on rtl/simmem_linkedlist_message_bank.sv
> +  for (genvar current_id = 0; current_id < 2 ** IDWidth; current_id = current_id + 1) begin
Don't forget the name for the generate block (these are missing in many cases)

```systemverilog
 for (genvar current_id = 0; current_id < 2 ** IDWidth; current_id = current_id + 1) begin : g_heads_actual
```

2020-06-30 15:29 UTC, GregAC commented on rtl/simmem_linkedlist_message_bank.sv
> +    ) begin
The `for` is easier to read if you can keep everything on one line, consider using a shorter index variable name to achieve this

```systemverilog
for(genvar i_bit = 0;i_bit < StructWidth; i_bit = i_bit + 1) : g_data_o_id_mask_rot90
```

2020-06-30 15:29 UTC, GregAC commented on rtl/simmem_linkedlist_message_bank.sv
> +      assign next_id_to_release_onehot[current_id] =
Either use an `always_comb` to allow the use of `if` statements or if this doesn't work well use comments to explain the intent of the statement. When it's a complex compound statement consider giving some of the sub-terms their own named signal to make it easier to understand what's going on.

2020-06-30 15:29 UTC, GregAC commented on rtl/simmem_linkedlist_message_bank.sv
> +      assign next_id_to_release_onehot[current_id] =
In the first instance focus on doing the simplest thing that could work. Here it looks like you're dealing with various corner cases where it may be simpler to avoid them by say delaying certain things a cycle.

2020-06-30 15:29 UTC, GregAC commented on rtl/simmem_write_resp_bank.sv
> +          addr_ram_id[ram_bank][ram_port][current_id] = '0;
It's not clear to me why you need per ID control signals for the RAM. For instance for the port used to write incoming requests only needs to write one thing, the data that applies to the incoming request. The write and req signals will be based on whether on or there is an incoming request.

What you don't have it multiple possible requests arbitrating for one port which is where you might need something like the structure you have here.

2020-06-30 15:29 UTC, GregAC commented on rtl/simmem_write_resp_bank.sv
> +  );
What data would a request need to have written into RAM when it comes in? I think it just needs a next_elem pointer so the message_ram may only need a single port for writing response data when it is received.

2020-06-30 15:29 UTC, GregAC commented on rtl/simmem_write_resp_bank.sv
> +  ) i_next_element_ram (
Rather than making this an explicit next_element_ram I'd make it a metadata_ram. For now this metadata may just be the next element pointer but it gives better scope for expansion to treat it this way.

2020-07-01 14:33 UTC, closed without merging

2020-07-08 08:38 UTC, flaviens commented on rtl/simmem_write_resp_bank.sv
> +  );
We'll discuss this in tomorrow's meeting, as it is indeed something that I had tried to do!

2020-07-08 08:40 UTC, flaviens commented on rtl/simmem_linkedlist_message_bank.sv
> +  logic [$clog2(TotalCapacity)-1:0] linkedlist_length_q[2**IDWidth-1:0];
We'll discuss this too!