Clean pr
lowRISC/gsoc-sim-mem pull request #2
Opened 2020-07-01 14:37 UTC by flaviens

Hi!

This PR contains the testbench C++ file, including three modes:
* A simple sequence of some known basic instructions.
* A randomized process on a single AXI identifier.
* A randomized process on multiple AXI identifiers.

Below is how to run the basic testbench and get access to the waveforms (will not compile for the moment)
```
fusesoc run --target=sim_write_resp_bank simmem
./build/simmem_0.1/sim_write_resp_bank-verilator/Vsimmem_write_resp_bank --trace#!/bin/sh
gtkwave write_resp_bank.fst
```

2020-07-06 13:55 UTC, vogelpi reviewed
Hi Flavien,
I did a first round of review and left a couple of comments. In general it is very difficult to review the code because there are almost no comments. This together with the relatively long signal names (that are very very similar) makes it very difficult for me to understand what the code should implement.

As next steps please:
1. Try to describe in short what the major code blocks try to implement.
2. Use shorter signal names to reduce the line wrapping and make the signal names better distinguishable.

This will it make easier for me and Greg to do the review. You can also start to implement some of the feedback.

In general, I think there is a lot of code related to translating between different signals variants (unpacked and packed of the various dimensions) that can simplified a lot. But let's first make sure we understand what's actually going on.

Regarding the commit history: you now have 49 commits (!) for an initial PR with 8 files. This is simply too much. We need at most 1 commit with the skeleton (directory structure, gitingore etc.) + 1 commit with simulation and 1 commit for the RTL file. Please also use meaningful commit messages. For some guidance, checkout this: https://github.com/lowRISC/ibex/blob/master/CONTRIBUTING.md including the embedded link.

2020-07-06 13:55 UTC, vogelpi commented on .clang-format
> +  Priority: 1
Missing newline. Please also check all other files.

2020-07-06 13:55 UTC, vogelpi commented on dv/simmem_write_resp_bank/cpp/simmem_write_resp_bank_tb.cc
> +  for (int i = 100; i < 1000; i++) {
Why do you start with `i = 100`?

2020-07-06 13:55 UTC, vogelpi commented on dv/simmem_write_resp_bank/cpp/simmem_write_resp_bank_tb.cc
> +    local_nb_mismatches = multiple_ids_test(tb, 5, i);
Ah now I see why you start at 100. `i` is actually your seed. This should be changed, also because the function expects an `unsigned int` whereas `i` is of type `int`.

2020-07-06 13:55 UTC, vogelpi commented on dv/simmem_write_resp_bank/cpp/simmem_write_resp_bank_tb.cc
> +  void stop_input_data() { module_->in_valid_i = 0; }
Some comments on functions names:
- I think they should be prefixed with `simmem_` not 100% sure though, you may want to check the coding style guidelines: https://docs.opentitan.org/doc/rm/c_cpp_coding_style/
- I recommend to rename these functions to `simmem_input_data_stop/apply()` and similarly `simmem_output_data_allow/forbid/request()`

2020-07-06 13:55 UTC, vogelpi commented on dv/simmem_write_resp_bank/cpp/simmem_write_resp_bank_tb.cc
> +  tb->apply_input_data(4 | (9 << kIdWidth));
What's the meaning of `4 | (9 << kIdWidth)`? You should at least put a comment.

2020-07-06 13:55 UTC, vogelpi commented on dv/simmem_write_resp_bank/cpp/simmem_write_resp_bank_tb.cc
> +size_t single_id_test(WriteRespBankTestbench *tb, unsigned int seed) {
Please comment on the function and interface: what does it require as inputs, what is the output, what does the function do?

2020-07-06 13:55 UTC, vogelpi commented on dv/simmem_write_resp_bank/cpp/simmem_write_resp_bank_tb.cc
> +    }
You should document what each of these functions do. It is for example not clear what the meaning of a reservation without applying input or requesting output data is? Is this meaningful at all? But the current function allows for that as `reserve, apply_input` and `request_output_data`  are randomized and independent.

Does the DUT also have three independent "channels"?

2020-07-06 13:55 UTC, vogelpi commented on rtl/simmem_write_resp_bank.sv
> +  input  logic [NumIds-1:0] reservation_request_id_onehot_i,
I would recommend to:
- use shorter signal names in general
- group signal names belonging to the same interface.

For example, here you could use `req_id_i, req_addr_o, req_ready_i, req_valid_o` and then `data_i, data_o,...` `rel_en_i, rel_addr_o,...`. This would make the code more readable.

2020-07-06 13:55 UTC, vogelpi commented on rtl/simmem_write_resp_bank.sv
> +  output logic reservation_request_valid_o,
The names and directions here are counter intuitive: Normally, the ready signal originates in the receptor and the valid signal in the requestor.

2020-07-06 13:55 UTC, vogelpi commented on rtl/simmem_write_resp_bank.sv
> +  output logic in_ready_o,
To which signals do this handshake signals belong? Data? release? Or both? This should be obvious from the naming or grouping or at least comments.

2020-07-06 13:55 UTC, vogelpi commented on rtl/simmem_write_resp_bank.sv
> +);
Indentation should be 2 chars for the parenthesis, 4 chars for the ports.

2020-07-06 13:55 UTC, vogelpi commented on rtl/simmem_write_resp_bank.sv
> +);
Same here.

2020-07-06 13:55 UTC, vogelpi commented on rtl/simmem_write_resp_bank.sv
> +    if (~rst_ni) begin
Nit: `(!rst_ni)`

2020-07-06 13:55 UTC, vogelpi commented on rtl/simmem_write_resp_bank.sv
> +  end
I think the loop here is not necessary, you can just do:
```
always_ff @(posedge clk_i or negedge rst_ni) begin
  if (~rst_ni) begin
    ram_valid_q <= '{default: '0};
  end else begin
    ram_valid_q <= ram_valid_d;
  end
end
```

2020-07-06 13:55 UTC, vogelpi commented on rtl/simmem_write_resp_bank.sv
> +  .a_rdata_o   (),
Also here, I would change the signal names: `msg_ram_in_req`, `msg_ram_in_we`, `msg_ram_in_wmask`, etc.

2020-07-06 13:55 UTC, vogelpi commented on rtl/simmem_write_resp_bank.sv
> +  end
I think this doesn't need to be in a loop, see comment below on `ram_valid_q`.

2020-07-06 13:55 UTC, vogelpi commented on rtl/simmem_write_resp_bank.sv
> +    METADATA_RAM = 1'b1
No need to explicitly define the values as long as you check against the enum values i.e. MESSAGE_/METADATA_RAM.

2020-07-06 13:55 UTC, vogelpi commented on rtl/simmem_write_resp_bank.sv
> +  // Piggyback signals translate the request that if the piggybacker gets updated in the next cycle, then follow it
This needs to be explained in more detail.

2020-07-06 13:55 UTC, vogelpi commented on rtl/simmem_write_resp_bank.sv
> +      assign next_free_ram_entry_onehot[0] = !ram_valid_q[0];
Nit: `~ram_valid_q[0]`

2020-07-06 13:55 UTC, vogelpi commented on rtl/simmem_write_resp_bank.sv
> +        next_free_ram_entry_onehot[current_addr] ? current_addr : '0;
This is not clean: I think `current_addr` is of type int (32 bit) whereas `next_free_ram_entry_onehot` is of type logic and different width. Also this signal is only used to get the `_rot90` version.

What you are actually trying to solve here is to get the index of the bit set in a one-hot signal. Can't you just to the following:
```
always_comb : begin
  next_free_ram_entry_binary = '0; // maybe the maximum value would be safer?
  for (int unsigned idx = 0; idx < TotalCapacity; idx = idx + 1) begin
    if (next_free_ram_entry_onehot[idx]) begin
      next_free_ram_entry_binary = idx[BankAddrWidth-1:0];
    end
  end
end
```

2020-07-06 13:55 UTC, vogelpi commented on rtl/simmem_write_resp_bank.sv
> +      |next_id_to_release_onehot || (!(out_valid_o && out_ready_i) && in_ready_o && in_valid_i);
?

2020-07-06 13:55 UTC, vogelpi commented on rtl/simmem_write_resp_bank.sv
> +  end : req_metadata_in_id_assignment
What does this code block do?

2020-07-07 17:25 UTC, flaviens commented on dv/simmem_write_resp_bank/cpp/simmem_write_resp_bank_tb.cc
> +    }
Yes, thank you for letting me know that it was not clear! There are indeed three "channels": one for reservation, one for input and one for output. I'll try to make that clearer in the code!

2020-07-07 17:42 UTC, flaviens commented on rtl/simmem_write_resp_bank.sv
> +  end
Alright! Actually I could not find another way to deal with unpacked arrays :/ . Could you provide me a little bit of help with this one please?

2020-07-07 17:44 UTC, flaviens commented on rtl/simmem_write_resp_bank.sv
> +  // Piggyback signals translate the request that if the piggybacker gets updated in the next cycle, then follow it
Okay! I added explanatory comments, please ask if more detail or better explanations are required!

2020-07-14 07:48 UTC, vogelpi commented on rtl/simmem_write_resp_bank.sv
> +  end
Can't you just do the following (without a loop)?
```
always_ff @(posedge clk_i or negedge rst_ni) begin
  if (~rst_ni) begin
    middles_q                    <= '{default: '0};
    ...
    is_middle_emptybox_q         <= '{default: '1};
    ...
    piggyback_tail_with_middle_q <= '{default: '0};
  end else begin
    middles_q                    <= middles_d;
    ... 
    is_middle_emptybox_q         <= is_middle_emptybox_d;
    ...
    piggyback_tail_with_middle_q <= piggyback_tail_with_middle_d;
  end
end
```

2020-07-14 08:00 UTC, flaviens commented on rtl/simmem_write_resp_bank.sv
> +  end
Yes, thanks! That worked perfectly!

2020-07-23 11:40 UTC, vogelpi commented on rtl/simmem_resp_bank.sv
> +  // mids are the pointers to the next address where the next input of the corresponding AXI
So this means `mids` is actually `heads_q + 1`. Wouldn't it be a lot simpler to generate `mids` based on `heads_q` instead of having separate tracking logic and a lot of flops?

2020-07-23 11:40 UTC, vogelpi commented on rtl/simmem_resp_bank.sv
> +// Message structure: The terms 'message' and 'response' are used interchangeably to refer to the
Please restrict yourself to one term and use that exclusively.

2020-07-23 13:43 UTC, vogelpi requested changes
Hi @flaviens ,

thanks for providing more documentation. That helps but it's still very difficult. For this reason, I did focus on one part: the handshake section. I have left quite some comments that are hopefully useful also for reworking other parts. Please let me know if you have questions.

Best,
Pirmin

2020-07-23 13:43 UTC, vogelpi commented on rtl/simmem_resp_bank.sv
> +// Message structure: The terms 'message' and 'response' are used interchangeably to refer to the
Please restrict yourself to one term and use that exclusively throughout the code.

2020-07-23 13:43 UTC, vogelpi commented on rtl/simmem_resp_bank.sv
> +  ) i_meta_ram_out_msg__head (
Nit: double underscore

2020-07-23 13:43 UTC, vogelpi commented on rtl/simmem_resp_bank.sv
> +        if (msg_heads[i_id] != tails[i_id]) begin
What does this condition `msg_heads[i_id] != tails[i_id]`? Does it mean the linkedlist is not empty or not full? If yes, please put a clarifying comment like:
```
// Output the message available at the tail and update the tail pointer.
```

2020-07-23 13:43 UTC, vogelpi commented on rtl/simmem_resp_bank.sv
> +        end else begin
Similarly, what's happening here? What do you mean by piggyback? Above you mentioned that the piggyback signals are used to handle corner cases. But you don't explain these corner cases. This makes it nearly impossible to understand what's going on or even debug/re-use the code.

Here you should put a comment like (not sure if this is what is going on):
```
// If the queue is full, we need to update both the tail and message head simultaneously. 
```

2020-07-23 13:43 UTC, vogelpi commented on rtl/simmem_resp_bank.sv
> +        // output according to the output handshake
This is not fully clear. If we have a handshake going on in the very cycle, we set the RAM address to the current tail. This means we get the actual data from the RAM in the next cycle (after the handshake). On the other hand, if we don't do a handshake at the moment, we feed the previous tail address to the RAM...

I think it would be much more natural to rename these tail pointers as follows:
- current `prev_tail` should be `tail` because that's really the tail of your queue. At this address is the last valid data in the RAM.
- current `tail` should be `next/pre_tail` because that's the second to the last element in your queue.

Then the addresses are fed to the RAM as follows:
- If you don't have a handshake at the moment, you feed `tail` to the memory. Consequently, you will have the current tail data ready in the next cycle.
- If you have a handshake at the moment, you feed `next/pre_tail` to the memory. Because at the moment you already have the data available that you need to output. What you care about is to get the data to potentially output in the next cycle (this is where `next/pre_tail` points to). 

This may sound like nitpicking but it's actually important to make the code more understandable. It took me around 10min to figure out what is happening here even though we were discussing this the day before yesterday.

2020-07-23 13:43 UTC, vogelpi commented on rtl/simmem_resp_bank.sv
> +          // If the reservation head is ahead of the middle pointer, then one can follow the pointer
There is no more middle pointer in your code. Please adapt the comment and other signal names like `mid_len_d/q`.

2020-07-23 13:43 UTC, vogelpi commented on rtl/simmem_resp_bank.sv
> +          pgbk_m_with_h[i_id] = 1'b1;
What does this condition signal? And what is the consequence, i.e., why do we set this piggyback signal?

2020-07-23 13:43 UTC, vogelpi commented on rtl/simmem_resp_bank.sv
> +  assign msg_ram_in_write = 1'b1;
Please don't do this. You seem to constantly set the write enable for the message RAM!

2020-07-23 13:43 UTC, vogelpi commented on rtl/simmem_resp_bank.sv
> +        msg_ram_in_addr_id[i_id] = msg_heads[i_id];
You should also set the write enable here. You probably again need a multi-bit signal and then reduce that down to `msg_ram_in_write` as you do for `msg_ram_in_write`.

2020-07-23 13:43 UTC, vogelpi commented on rtl/simmem_resp_bank.sv
> +          end
Again, you need to explain what these conditions mean and to what actions they lead here.

2020-07-23 14:02 UTC, flaviens commented on rtl/simmem_resp_bank.sv
> +        if (msg_heads[i_id] != tails[i_id]) begin
Not exactly, but that's a good remark, I have added a comment which unambiguously answers this question. Thanks!

2020-07-23 14:20 UTC, flaviens commented on rtl/simmem_resp_bank.sv
> +        // output according to the output handshake
That's a much more meaningful notation. It is integrated now. Thanks!

2020-07-23 14:22 UTC, flaviens commented on rtl/simmem_resp_bank.sv
> +  assign msg_ram_in_write = 1'b1;
Yes, I did not know this was a problem. Is it energy consuming? (there is another input for req, and without req nothing happens anyways). Should I AND the write enable with the request boolean signal?

2020-07-23 14:35 UTC, flaviens commented on rtl/simmem_resp_bank.sv
> +        msg_ram_in_addr_id[i_id] = msg_heads[i_id];
Actually, the message RAM (newly renamed response RAM, so let's call it like this from now on) has one port only dedicated to reads and one dedicated to writes. Is it a bad practice?

2020-07-24 07:26 UTC, vogelpi commented on rtl/simmem_resp_bank.sv
> +  assign msg_ram_in_write = 1'b1;
Yes, it's energy consumption (we could say we don't care about this here) but also very bad practice in general. The write enable should factor in both the valid_i and the ready_o: Only if you have a handshake, you should write to the memory.

2020-07-24 07:35 UTC, flaviens commented on rtl/simmem_resp_bank.sv
> +  assign msg_ram_in_write = 1'b1;
Okay! Then should I just assign it to be equal to msg_ram_in_req?

2020-07-24 07:44 UTC, vogelpi commented on rtl/simmem_resp_bank.sv
> +        if (msg_heads[i_id] != tails[i_id]) begin
Sorry but this is still not clear. Your comment is basically the long form of the SystemVerilog statement. It does not add useful information as it does not describe what the conditions means or how we are going to react on the condition. The comment should explain:
1. What does it mean if the response head is not at the same address of the pre_tail? Is our queue empty/not empty? do we have more/less than one item to output?
2. What does it mean to piggyback the pre_tail with the response head? Do we update both because we simultaneously read and write?
These are the things that your comments should explain. They should not be just a long form of the code.

2020-07-24 07:44 UTC, vogelpi commented on rtl/simmem_resp_bank.sv
> +        end else begin
Same here, it is still not clear.

2020-07-24 07:49 UTC, vogelpi commented on rtl/simmem_resp_bank.sv
> +        msg_ram_in_addr_id[i_id] = msg_heads[i_id];
This is perfectly fine. On Xilinx FPGAs you have true dual-port memories (you can read and write on both ports). In ASIC technology also two-port memories are common. These are a bit cheaper in terms of area but you can only read on one port and write on the other one. And then you also have single-port memories...

2020-07-24 07:58 UTC, flaviens commented on rtl/simmem_resp_bank.sv
> +        msg_ram_in_addr_id[i_id] = msg_heads[i_id];
Alright thank you for your answer!

2020-07-24 08:23 UTC, vogelpi reviewed
GitHub tells me I need to submit my review before doing further comments.

2020-07-24 08:24 UTC, vogelpi commented on rtl/simmem_resp_bank.sv
> +  assign msg_ram_in_write = 1'b1;
Yes, using `payload_ram_in_req` sounds right.

2020-07-24 08:53 UTC, flaviens commented
> GitHub tells me I need to submit my review before doing further comments.

I re-converted into a draft-PR. I hope it solves the problem!

2020-07-25 12:26 UTC, vogelpi requested changes
Hi @flaviens ,
I had another look. It looks much better now. In general, I have the impression your comments are very verbose and detailed. You try to capture every special case and sometimes use nested relative sentences. This makes it quite difficult to follow. Also, the comments are sometimes a bit repetitive but with slightly different wording which does not help either. I have left another set of comments that hopefully allow you to understand what I mean and show you how to improve the documentation further. 

Also, there is some dead that can be removed to further simplify the thing.

Please do not resolve the discussions as PR author. Except for very obvious changes like typos, alignment stuff etc. the reviewer closes the discussions if the comments have been addressed sufficiently.

Best,
Pirmin

2020-07-25 12:26 UTC, vogelpi commented on rtl/simmem_resp_bank.sv
> +        // there is one, else to the response head).
```
// The pre_tail must point to
// - the second-to-last element of the linked list if the list contains two reponses or more,
// - the last element element of the linked list if the list contains just one response,
// - rsp_head if the list contains no responses.

2020-07-25 12:26 UTC, vogelpi commented on rtl/simmem_resp_bank.sv
> +        //  piggybacking operation.
That's a useful comment. It adds really useful information, bravo!  :+1:

2020-07-25 12:26 UTC, vogelpi commented on rtl/simmem_resp_bank.sv
> +        //  piggybacking operation.
I would split it up and move it down directly to the relevant section in the if/else. See comments below.

2020-07-25 12:26 UTC, vogelpi commented on rtl/simmem_resp_bank.sv
> +          // If possible, update the fail from the linkedlist pointers stored in RAM.
Replace this comment by what you have above:
```
// If the rsp_head is not at the same address as the pre_tail, then the pre_tail can be
// safely updated from the RAM without risking to overtake the response pointer.
```

2020-07-25 12:26 UTC, vogelpi commented on rtl/simmem_resp_bank.sv
> +          // remains blocked with it.
Replace this comment by what you have above:
```
// If the pre_tail points to the same value as the rsp_head, then to respect the pointer
// ordering (precisely here, pre_tail <= rsp_head in the order defined by the linked list),
// the pre_tail must be updated only if the response head is updated (piggybacking). This
// also covers the case  "pre_tail == rsp_head == rsv_head AND current reservation
// handshake is taking place".
```

2020-07-25 12:26 UTC, vogelpi commented on rtl/simmem_resp_bank.sv
> +        // output according to the output handshake.
```
// The pre_tail points not to the current output to provide, but to the next. If we currently provide
// output (handshake), make sure to be ready in the next cycle. The RAM has a read latency of one
// clock cycle.

2020-07-25 12:26 UTC, vogelpi commented on rtl/simmem_resp_bank.sv
> +          update_rsp_from_ram_d[i_id] = 1'b1;
Split and move the comment above here:
```
// If the reservation head is ahead of the response head, then the rsp_head can follow
// the pointer from the metadata RAM.
```
Please note your original comment above is actually wrong. It's not the reservation head that is following (referred to by "it" in the relative sentence) but the response head.

2020-07-25 12:26 UTC, vogelpi commented on rtl/simmem_resp_bank.sv
> +          pgbk_rsp_with_rsv[i_id] = 1'b1;
Split and move the comment above here:
```
// Else, both rsp_head and rsv_head need to be updated (piggybacking).
```
Question, how is the case handled when we need to update both rsp_head and rsv_head because of an input handshake, but we don't get a reservation handshake? Is that even possible?

2020-07-25 12:26 UTC, vogelpi commented on rtl/simmem_resp_bank.sv
> +          // Fullbox if could not move forward
This comment is not clear and confusing. The comment speaks of a "fullbox" whereas the signal assigned is called `*_emptybox_d`.

If I understand it correctly, you check here if `rsv_heads_q` is going to change, i.e., if we actually push a new reservation. What is the consequence of this?

2020-07-25 12:26 UTC, vogelpi commented on rtl/simmem_resp_bank.sv
> +        // response head.
This can be shortened and simplified substantially:
```
// If the response queue is going to be empty in the next clock cycle, me must
// update the pre_tail together with rsp_head (piggybacking).
```
Question: This code segments seems to be pretty much at the wrong place. In this section we are primarily dealing with input handshaking. But this segment evaluates what happens at the output and defines if the pre_tail needs to be updated. Shouldn't this be moved to where we deal with the output and pre_tail updates anyway?

2020-07-25 12:26 UTC, vogelpi commented on rtl/simmem_resp_bank.sv
> +                pgbk_pt_with_rsv[i_id] = 1'b1;
This is dead code, it can never ever be reached. You only ever enter the block on Line 688 if `rsp_len_after_out != 0` and `rsv_len_q == 0` (see also Line 675). Also your comment inidcates this: "If the rsp_len_after_out is zero, it means that a brand new queue is being initiated..." this case is already handled below on Line 708.

2020-07-25 12:26 UTC, vogelpi commented on rtl/simmem_resp_bank.sv
> +                pgbk_pt_with_rsv[i_id] = 1'b1;
So this whole section from Line 675 to 707 can be simplified a lot as follows:
```SystemVerilog
        // If the queue is already initiated, then update the head position in the RAM.
        if (|rsv_len_q[i_id] || |rsp_len_after_out[i_id]) begin : reservation_initiated_queue
          meta_ram_in_addr_id[i_id] = rsv_heads_q[i_id];
          meta_ram_in_content_id[i_id].nxt_elem = nxt_free_addr;

          if (rsv_heads_q[i_id] == rsp_heads[i_id]) begin
            if (rsv_len_q[i_id] == 0) begin
              // The rsp_head is placed on a reserved RAM address, but it could not yet
              // be updated to the next reserved address in the linked list, as this next
              // address has not yet been reserved. In case rsv_head is updated, make
              // sure to also update rsp_head (piggybacking) to have rsp_head pointing
              // to next free reserved address.
              pgbk_rsp_with_rsv[i_id] = 1'b1;
              is_rsp_head_emptybox_d[i_id] = 1'b1;

              // Also update pre_tail with rsv_head, it was blocked behind rsp_head.
              // Note that rsp_len_after_out != 0, hence rsv_len_q == 0. Further we
              // have rsv_heads_q == rsp_heads.  
              if (rsp_len_after_out[i_id] == 1) begin
                pgbk_pt_with_rsv[i_id] = 1'b1;
              end
            end
          end
        end
```

2020-07-26 08:08 UTC, flaviens commented on rtl/simmem_resp_bank.sv
> +        // there is one, else to the response head).
That's very clear! I'll try do do similar improvements on other comments as well where applicable.

2020-07-26 08:12 UTC, flaviens commented on rtl/simmem_resp_bank.sv
> +          // If possible, update the fail from the linkedlist pointers stored in RAM.
Done!

2020-07-26 08:12 UTC, flaviens commented on rtl/simmem_resp_bank.sv
> +          // remains blocked with it.
Done!

2020-07-26 08:13 UTC, flaviens commented on rtl/simmem_resp_bank.sv
> +        // output according to the output handshake.
Done!

2020-07-26 08:14 UTC, flaviens commented on rtl/simmem_resp_bank.sv
> +          update_rsp_from_ram_d[i_id] = 1'b1;
Yes your remark is exact, "it" was badly expressed. Done!

2020-07-26 08:20 UTC, flaviens commented on rtl/simmem_resp_bank.sv
> +          pgbk_rsp_with_rsv[i_id] = 1'b1;
Actually, the reservation head position and must never depend on an input handshake. I believe this was not really clear because the comment proposal
```
// Else, both rsp_head and rsv_head need to be updated (piggybacking).
```
does not go in this direction. I'm trying to make that clearer.

2020-07-26 08:38 UTC, flaviens commented on rtl/simmem_resp_bank.sv
> +          // Fullbox if could not move forward
This comment along with the following line were artifacts from previous versions, which were left unnoticed. Thank you for the question! So the answer is, I'll just remove this.

2020-07-26 08:47 UTC, flaviens commented on rtl/simmem_resp_bank.sv
> +        // response head.
Thank you again for the question!
Actually, a good indicator to see if a similar piece of code is placed in the right handshake is to look at the LHS of the piggyback signal assignment, in this case _pgbk_pt_with_rsp_d_.

This indicates, that there will be in any case no update of the pre_tail if there is no update of the response head. And the response head is only updated on an input handshake.
Conversely, the _if_ condition does not require an output handshake to be true.

Therefore I believe it cannot easily be placed elsewhere.

2020-07-26 08:54 UTC, flaviens commented on rtl/simmem_resp_bank.sv
> +                pgbk_pt_with_rsv[i_id] = 1'b1;
Correct & much more elegant. Done!

2020-07-29 07:39 UTC, vogelpi commented on rtl/simmem_resp_bank.sv
> +          pgbk_rsp_with_rsv[i_id] = 1'b1;
Now I am even more confused. First of all, your comment now says:
```
// Else, rsp_head needs to be updated by piggybacking with rsp_head.
```
Second, you didn't answer my question: What happens if `pgbk_rsp_with_rsv` is set but we don't get a reservation handshake (in which case we don't update rsv_head but we want to update rsp_head and they point to the same address)?

2020-07-29 07:39 UTC, vogelpi commented on rtl/simmem_resp_bank.sv
> +          // Fullbox if could not move forward
Okay, sounds good.

2020-07-29 07:48 UTC, vogelpi commented on rtl/simmem_resp_bank.sv
> +        // response head.
Alright, thanks for explaining that. It's now much clearer what piggybacking actually is (a conditional update). It was not clear to me that `pgbk_a_with_b` means: update `a` if also `b` is updated.

I see that you also added another comment at the beginning of the file regarding that. Thanks, that is very helpful.

2020-07-29 07:53 UTC, flaviens commented on rtl/simmem_resp_bank.sv
> +          pgbk_rsp_with_rsv[i_id] = 1'b1;
Thank for the review and sorry for the typo and insufficient explanations!
I have updated the PR to solve it.

2020-07-29 07:54 UTC, flaviens commented on rtl/simmem_resp_bank.sv
> +        //  piggybacking operation.
Didn't mention it last time, but has been done, too.

2020-07-29 08:06 UTC, vogelpi approved these changes
Hi @flaviens
thanks for integrating my comments once more. The overall functionality is now much clearer, better commented and documented, and implemented in a cleaner way.

I did not do another full review as I have already spent much more time on this PR than what I normally do. But I think the design has improved a lot in the review process and we have now reached a level of quality that is acceptable. Also, I believe you have learned quite a lot which should ease the process in the future. I suggest to merge this (after the last remaining comment has been fixed).

Best,
Pirmin

2020-07-29 08:06 UTC, vogelpi commented on rtl/simmem_resp_bank.sv
> +          pgbk_rsp_with_rsv[i_id] = 1'b1;
Correction: my question is answered `pgbk_rsp_with_rsv` just means we want to update `rsp` in case also `rsv` is updated but not otherwise.

What remains is to correct the comment in the code. It makes little sense at the moment.

2020-07-29 08:10 UTC, vogelpi commented
Just noted that you already fixed that last outstanding comment :-)

You can convert this again to real PR (not draft) and we can proceed.

2020-07-29 11:13 UTC, flaviens commented
I've made a series of small modifications to improve comment line wrapping and signal name consistency. The series of improvements should be complete now.

2020-08-03 08:56 UTC, merged